### ISSUE TITLE
Stuck while trying to deploy to heroku

### ISSUE THREAD

**Issue by OmgImAlexis** [FoxxMD/context-mod#29]
Used the heroku link and then provided it the needed envs.

The site shows a heroku error and when trying to connect via `heroku run bash` it never connects.
It's just forever showing `Running bash on ⬢ context-mod... / connecting, run.4890 (Hobby)`.

Any ideas if this is a heroku issue or something with the deploy?

**Comment by FoxxMD** [comment]
In [v10.0.2](https://github.com/FoxxMD/context-mod/releases/tag/0.10.2) I've made changes to the heroku deployment template so this actually works now as well as updated documentation to make usage clearer and point out some caveats.
